# Site settings
title: Likewise
email: your-email@domain.com
description: > # keep this and put description below
  The band of all time
url: "https://likewise.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/gamingportfolio"
github_username: musicportfolio
twitter_username: musicportfolio
footer_text: "This site is 100% gluten free. (Change this later)"

# Build settings
markdown: kramdown
permalink: pretty
